### PR TITLE
Add e2e tests

### LINKED ISSUE #15: e2e coverage
At the current stage, we're missing any e2e coverage,

Furthermore, we have to run an e2e test for each supported infrastructure provider.

### PR DESCRIPTION
**Pull request by dineshba**
Create new e2e github actions workflow and resolves #15 

### Test coverage:
- Running cluster-api-control-plane-provider-kamaji and validate no crashes
- Creating target cluster using cluster-api-control-plane-provider-kamaji and kubevirt infra provider
- Validate the cluster, kamajicontrolplane CR's readiness
- Validate the worker CRs like Machine, Kubevirt-pod readiness
- Fetch the kubeconfig of target cluster and install calico CNI
- Validate the readiness of target cluster node

Successfully run: https://github.com/dineshba/cluster-api-control-plane-provider-kamaji/actions/runs/11303188257/job/31439998988
Screenshot:
image

### CODE REVIEW

**Comment by dineshba** [comment]
Hi @prometherion, please help in review and provide your inputs. It has the basic validations as described in the PR description

**Comment by prometherion** [comment]
I'd say this is a good starting point, thanks for it.

I would avoid installing the Kamaji Control Plane provider using the already published manifests, but rather, I'd use the ones available in the checked out, as well as load the container image to the `kind` instance: if you prefer, I can take care of these actions with a subsequent PR.

**Comment by dineshba** [comment]
I totally agree with the PR based manifests and images. I can either add to this PR or create new PR. Please share your inputs

**Comment by prometherion** [comment]
I would prefer having everything in one single PR, thanks!

**Comment by dineshba** [comment]
Hi @prometherion, Please review the latest commit https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/130/commits/fb6d8ed93c3465be3b8babbf1317703df82a5d29

#### What is done:
- build docker image
- Loaded that docker image into Kind
- Changed the manifests to point to new docker image
- Configure clusterctl to get config files from local instead of released artifacts
- Validated if the right image is used or not

**Comment by prometherion** [comment]
@dineshba we can ignore the `golangci-lint` stage, I'll fix it later since I merged a non linted PR, my bad. Thanks for your contribution! 🙏🏻

**Pull request merged**
