### PR TITLE
Support for additional printer columns

### LINKED ISSUE #67: Need to add print columns
CAPI KCP(kamajicontrolplane) needs more print columns that provide information about itself.
- Is TCP(tenant control plane) deployed? : TCP AVAILABLE
- are the resources for linking with CAPI (CA secret, kubeconfig) deployed? : INITIALIZED
- something like that

For example,

(before) CAPI kamajicontrolplane
```
ubuntu@kamaji:~/capi-db-sync$ k get kamajicontrolplane -o wide
NAME                    AGE
kamajicontrolplane-28   19h
```

(after) CAPI kamajicontrolplane
```
ubuntu@kamaji:~/capi-db-sync$ k get kamajicontrolplane -o wide
NAME                        INITIALIZED              TCP AVAILABLE  VERSION   STATUS  AGE
kamajicontrolplane-28            true                     true      v1.28.2   Ready      19h
```

### PR DESCRIPTION
**Pull request by prometherion**
Closes #67.

### CODE REVIEW

**Comment by prometherion** [comment]
```
$: kubectl get kamajicontrolplanes.controlplane.cluster.x-k8s.io
NAME                       VERSION   INITIALIZED   READY   AGE
capi-quickstart-kubevirt   1.23.10   true          true    60d
```

@jds9090 WDYT?

**Comment by jds9090** [comment]
> ```
> $: kubectl get kamajicontrolplanes.controlplane.cluster.x-k8s.io
> NAME                       VERSION   INITIALIZED   READY   AGE
> capi-quickstart-kubevirt   1.23.10   true          true    60d
> ```
> 
> @jds9090 WDYT?

Just to double check as below

- INITIALIZED means ControlPlaneEndpoint, Infrastructure and TCP(Tenant Control Plane) are ready
- READY means ControlPlaneEndpoint, Infrastructure, TCP(Tenant Control Plane) and Required resources(CA secret, Kubeconfig) are ready

Is it right?

**Comment by prometherion** [comment]
The initialized is for the TCP resource has been accepted by Kamaji which is processing it, but still unknown if the given configuration leads to a working Control Plane.

**Comment by jds9090** [comment]
> The initialized is for the TCP resource has been accepted by Kamaji which is processing it, but still unknown if the given configuration leads to a working Control Plane.

LGTM

**Pull request merged**
